projects:
  - name: portfolio
    environments:
      - name: production
        services:
          - type: web
            runtime: image
            name: portfolio-backend
            image:
              url: ghcr.io/zorionten/portfolio-backend:main
            plan: free
            region: singapore
            healthCheckPath: /actuator/health
            envVars:
              - key: SPRING_DATASOURCE_URL
                sync: false
              - key: SPRING_DATASOURCE_USERNAME
                sync: false
              - key: SPRING_DATASOURCE_PASSWORD
                sync: false
              - key: GITHUB_API_TOKEN
                sync: false
              - key: AI_SERVICE_URL
                value: https://portfolio-ai-dla4.onrender.com
          - type: web
            runtime: image
            name: portfolio-ai
            image:
              url: ghcr.io/zorionten/portfolio-ai:main
            plan: free
            region: singapore
            healthCheckPath: /health
            envVars:
              - key: GROQ_API_KEY
                sync: false
              - key: GITHUB_KNOWLEDGE_URL
                value: https://portfolio-backend-lutt.onrender.com/api/github/knowledge
              - key: SKILLS_FILE
                value: /etc/secrets/JOB_APPLICATION_MASTER.md
